export default {
  TITLE: "Media - VUW Women in Tech",
  HEADING: "Newsletters, Blogs & Documents",
  NEWSLETTER_ARCHIVE: "Newsletter Archive",
  AUG18: "August 2018",
  SEP18: "September 2018",
  OCT18: "October 2018",
  FEB19: "February 2019",
  MAR19: "March 2019",
  APR19: "April 2019",
  MAY19: "May 2019",
  JUN19: "June 2019",
  TECHWEEK19: "Tech Week 2019",
  JUL19: "July 2019",
  AUG19: "August 2019",
  SEP19: "September 2019",

  BLOG_POSTS_MEDIA: "Blog Posts & Media",
  STEM_FIELDS_CONTINUE_STRUGGLE_DIVERSITY: "STEM fields continue to struggle with diversity",
  RUNNING_DIVERSE_TECH_CONF: "Running a diverse tech conference",
  SPOTLIGHT_ON_STRONG_WOMEN: "Spotlight on the strong women in tech at VUW",
  WITCON_RECAP_KNFRANCES: "WITcon 2018 recap - knfrances",
  CELEBRATING_IGICTD: "Celebrating International Girls in ICT Day",
  TECHWEEK_RECAP: "TechWeek19: Leaders, lightning talks and lattes",
  HACKATHON_RECAP: "a hackathon as an intro to hackathons",
  SHECANCODE_ALEISHA: "SheCanCode Coder Stories: Aleisha Amohia",
  PRESIDENTS_REPORT_18: "VUWWIT President's Report 2018",
  ACCESS_GRANTED: "Aleisha Amohia - a good mix of tech stuff and people stuff",
  CAREERS_WITH_STEM: "Junior Developer at VUW | Careers with STEM",
  TDFG_REVIEW: "Tech Day for Girls 2019 Review",

  DOCUMENTS: "Official Documents",
  CONSTITUTION2020: "Constitution 2020",
  ROLES2020: "Committee Roles & Responsibilities 2020",
  AGM2019: "AGM Minutes 2019",
  CODE_OF_CONDUCT: "Code of Conduct",
  AGM2018: "AGM Minutes 2018",
  IGM2018: "IGM Minutes 2018",
};
