export default {
    TITLE: "Mentoring Circles - VUW Women in Tech",
    MENTORING_CIRCLES: "Mentoring Circles",
    VUWWITS_GOAL: "VUWWIT’s goal is to grow a strong community of diverse people in tech, and ensure they are supported and developed in all stages of their careers.",
    IN_ORDER_TO: "In order to achieve this, we’ve decided to set up mentoring circles within VUW, so that students can get a headstart on their career development and industry can get some quality time with driven, dedicated students. It’s an opportunity for people at all stages of their studies or careers to sit down together, talk about their journeys and learn from each other.",
    WERE_AWARE_THAT: "We’re aware that everyone is extremely busy and may not be able to commit to a formal one-on-one mentorship match-up, which is why we are trialling a mentoring circle programme. We are facilitating groups of 6-8 mentees and mentors to meet regularly in a safe and supportive environment.",
    KEY_DATES: "Key Dates:",
    DATE: "Date",
    TIME: "Time",
    VENUE: "Venue",
    ONE: "Session One",
    TWO: "Session Two",
    THREE: "Session Three",
    FOUR: "Session Four",
    FIRST_SESSION: "Tuesday 9th April",
    SECOND_SESSION: "Tuesday 28th May",
    THIRD_SESSION: "Tuesday 13th August",
    FOURTH_SESSION: "Tuesday 1st October",
    FIVE_THIRTY: "5:30pm",
    AM103: "AM103, Alan MacDiarmid building, Kelburn Campus",
    ATTENDING_ALL: "It is not necessary for you to attend every session, however it is ideal if you can. If there are dates you know you are unavailable, please indicate this in the form when you register.",
    WHAT_IT_IS: "What it is",
    IS_ONE: "Facilitated peer group mentoring",
    IS_TWO: "Group discussion of non-technical aspects of career development (e.g. how to work with other people, how to deal with management, how to ask for a promotion)",
    IS_THREE: "Career path planning and development",
    IS_FOUR: "Networking with new people",
    WHAT_IT_IS_NOT: "What it is not",
    ISNT_ONE: "Formal or structured",
    ISNT_TWO: "One-on-one coaching",
    ISNT_THREE: "Mentoring training (e.g. tools/techniques for mentoring)",
    ISNT_FOUR: "Technical training/coaching",
    BENEFITS: "Benefits of a Circle",
    BENEFIT_ONE: "Mentees benefit from multiple mentors",
    BENEFIT_TWO: "Feedback from peers as well as a mentor will provide the mentee with more diverse points of view and a variety of insights",
    BENEFIT_THREE: "It will create a support network with local women in technology",
    BENEFIT_FOUR: "The group context will create opportunities for teamwork/collaboration on issues",
    BENEFIT_FIVE: "A circle will create a conversational style of mentoring which is less formal than one-on-one",
    BENEFIT_SIX: "A wide variety of topics will be covered",
    HOW_TO_APPLY: "How to Apply",
    TO_REGISTER: "Registrations for the 2019 VUWWIT Mentoring Circles have now closed.",
    //REGISTER: "Register"
};